# Generated by Django 6.0 on 2025-12-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstr1vs3b', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('gstin', models.CharField(max_length=15)),
                ('access_token', models.TextField()),
                ('taxpayer_token', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
