# Generated by Django 6.0 on 2025-12-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstr1vs3b', '0002_gstsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='gstsession',
            name='gstin',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='gstsession',
            name='session_key',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='gstsession',
            index=models.Index(fields=['session_key', 'created_at'], name='gstr1vs3b_g_session_1df53c_idx'),
        ),
    ]
