# Generated by Django 6.0 on 2025-12-08 12:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstr1vs3b', '0003_alter_gstsession_created_at_alter_gstsession_gstin_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gstsession',
            name='gstr1vs3b_g_session_1df53c_idx',
        ),
        migrations.AddField(
            model_name='gstsession',
            name='session_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.RemoveField(
            model_name='gstsession',
            name='session_key',
        ),
    ]
