# Generated by Django 5.0.14 on 2025-12-31 05:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedGSTSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('gstin', models.CharField(max_length=15)),
                ('access_token', models.TextField(blank=True, help_text='Initial sandbox access token', null=True)),
                ('taxpayer_token', models.TextField(blank=True, help_text='Token after OTP verification', null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'unified_gst_session',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id'], name='unified_gst_session_04c593_idx'), models.Index(fields=['gstin', 'is_verified'], name='unified_gst_gstin_3064d1_idx')],
            },
        ),
    ]
