# Generated by Django 5.0.14 on 2026-01-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(help_text='Sandbox API access token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Token expiry time (24 hours from creation)')),
            ],
            options={
                'db_table': 'sandbox_access_token',
            },
        ),
    ]
