# Generated by Django 5.2.8 on 2025-12-05 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactquery',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={},
        ),
    ]
