# Generated by Django 5.0.14 on 2026-01-02 10:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GSTSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('gstin', models.CharField(max_length=15)),
                ('access_token', models.TextField(blank=True, help_text='Sandbox auth token', null=True)),
                ('taxpayer_token', models.TextField(blank=True, help_text='Token after OTP verification', null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'GST Session',
                'verbose_name_plural': 'GST Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
